apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: innogen-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: innogen.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: innogen-backend
                port:
                  number: 3000
