apiVersion: v1
kind: Secret
metadata:
  name: innogen-secrets
  labels:
    app: innogen
type: Opaque
stringData:
  GROQ_API_KEY: "gsk_..."
  GEMINI_API_KEY: "AI..."
  SEARCH_API_KEY: "..."
  TAVILY_API_KEY: "tvly-..."
  POSTGRES_PASSWORD: "innogen_secret"
